Repository borismus/keysocket, pull requests merged in 2019-03, with the labels that each got.

#286 LinkedIn learning
  extension/keysocket-linkedin-learning.js
  extension/manifest.json
Labels: new-service

#301 Fix Plex and openload support
  README.md
  extension/keysocket-iplayer.js
  extension/keysocket-openload.js
  extension/keysocket-plex.js
  extension/manifest.json
  extension/plugin-api.js
Labels: compatibility-break, new-service

#310 Add noisli.com support
  README.md
  extension/keysocket-noisli.js
  extension/manifest.json
Labels: new-service

#313 Add mx3creations.com
  extension/keysocket-mx3creations.js
  extension/manifest.json
Labels: new-service

#317 bugfix: Tidal: changes to accommodate ui changes
  extension/keysocket-tidal.js
Labels: compatibility-break

#318 Support jamendo.com.
  README.md
  extension/keysocket-jamendo.js
  extension/manifest.json
Labels: new-service
